<ul class="service_list_box">
                                       <li><a href="balcony-safety-nets.php">Balcony Safety Nets</a> </li>
                                       <li><a href="pigeon-safety-nets.php">Pigeon Safety Nets</a> </li>
                                       <li><a href="children-safety-nets.php">Children Safety Nets</a> </li>
                                       <li><a href="duct-area-safety-nets.php">Duct Area Safety Nets</a> </li>
                                       <li><a href="cricket-practice-nets.php">Cricket Practice Nets</a> </li>
                                       <li><a href="glass-safety-nets.php">Glass Building Safety Nets</a> </li>
                                       <li><a href="industrial-safety-nets.php">Industrial Safety Nets</a> </li>
                                       <li><a href="swimming-pool-safety-net.php">Swimming Pool Safety Nets</a> </li>
                                       <li><a href="staircase-safety-nets.php">Staircase Safety Nets</a> </li>
                                       <li><a href="monkey-safety-nets.php">Monkey Safety Nets</a> </li>
                                       <li><a href="construction-safety-nets.php">Construction Safety Nets</a> </li>
                                       <li><a href="coconut-safety-nets.php">Coconut Safety Nets</a> </li>
                                       <li><a href="mosquito-nets.php">Mosquito Nets</a> </li>
                                       <li><a href="sports-nets.php">All Sports Practice Nets</a> </li>
                                       <li><a href="bird-spikes.php">Bird Spikes</a> </li>
                                       <li><a href="bird-protection-nets.php">Bird Protection Nets</a> </li>
                                       <li><a href="anti-bird-nets.php">Anti Bird Nets</a> </li>
                                       <li><a href="pigion-nets-for-balconies.php">Pigeon Nets for Balconies</a> </li>
                                       <li><a href="agro-shade-nets.php">Agro Shade Nets</a> </li>
                                       <li><a href="plant-support-netting.php">Plant Support Netting</a> </li>
                                       <li><a href="garden-nettting.php">Garden Netting</a> </li>
                                       <li><a href="shade-nets.php">Shade Nets</a> </li>
                                       <li><a href="carparking-safety-net.php">Car Parking Safety Net</a> </li>
                                    </ul>